spring:
  application:
    name: module01-actuator
  datasource:
    url: jdbc:mysql://localhost:3306/popular_shop
    username: wanted
    password: wanted
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always

logging:
  level:
    root: info
